Fix --setpoweroverdrive type conversion
Here python returns the string value of getSysfsValue cast to int
then dividing by 1000000 returns a float string for min(0.0) & max(145.0) power cap
Casting those to int in the comparison breaks python rules (precision loss)
A fix would be to first cast to float and then to int - but this is bad.
```python
        max_power_cap = str(int(getSysfsValue(device, 'power_cap_max')) / 1000000)
        min_power_cap = str(int(getSysfsValue(device, 'power_cap_min')) / 1000000)

        if int(value) < int(min_power_cap):
```

Instead avoid early div by 1 000 000, the kernel already uses microWatt values,
dividing these can give floating point results which cause problems.
For example when attempting to set poweroverdrive in the prior code:

```
Traceback (most recent call last):
  File "/usr/bin/rocm-smi", line 1506, in <module>
    setPowerOverDrive(deviceList, args.setpoweroverdrive, args.autorespond)
  File "/usr/bin/rocm-smi", line 1098, in setPowerOverDrive
    if int(value) < int(min_power_cap):
ValueError: invalid literal for int() with base 10: '0.0'
```

This patch fixes this by instead setting up input value as microWatt to avoid
unnecessary conversions that may yield floats where important.
 - string output excluded.

Brought in from:
https://github.com/RadeonOpenCompute/ROC-smi/pull/48

v2: Fixed up the comment for this function to correctly describe 'value' -jlg

Signed-off-by: Rigo Reddig <rigo.reddig@gmail.com>

Change-Id: If7fc02f1c9c983037efced1b871bba8c464f20b3