fix a bug causing KeyError in setpoweroverdrive
[Error Log]
sudo rocm-smi --setpoweroverdrive 125
Traceback (most recent call last):
  File "/usr/bin/rocm-smi", line 1910, in <module>
    setPowerOverDrive(deviceList, args.setpoweroverdrive, args.autorespond)
  File "/usr/bin/rocm-smi", line 1396, in setPowerOverDrive
    power_cap_path = getFilePath(device, 'power1_cap')
  File "/usr/bin/rocm-smi", line 130, in getFilePath
    pathDict = valuePaths[key]
KeyError: 'power1_cap'
[FIX]
Line 1396，change `power1_cap` to `power_cap` fixed the error.